name: Test CI Django 2

on:

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11.0
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Database setup
        run: |
          python manage.py migrate

      - name: Lint with flake8
        run: |
          flake8 
      - name: Django testing
        run: |
          python manage.py test

  check_workflow_status:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check workflow status
        id: check_status
        run: echo "Workflow status is ${{ job.status }}"

  merge_on_success:
    needs: check_workflow_status
    runs-on: ubuntu-latest
    if: ${{ needs.build.result == 'success' }}

    steps:
      - name: Merge pull request
        run: echo "Merge pull request"  