name: Test CI Django

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11.0
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Database setup
        run: |
          python manage.py migrate

      - name: Django testing
        run: |
          python manage.py test
